namespace TechanCore.Enums
{
	public enum CandlePatterns
	{
		DOJI,
		SHOOTING_STAR,
		BEARISH_EVENING_STAR,
		BULLISH_MORNING_STAR,
		BULLISH_HAMMER,
		BEARISH_INVERTED_HAMMER,
		BEARISH_HARAMI,
		BULLISH_HARAMI,
		BEARISH_ENGULFING,
		BULLISH_ENGULFING,
		PIERCING_LINE,
		BULLISH_BELT,
		BULLISH_KICKER,
		BEARISH_KICKER,
		BEARISH_HANGING_MAN,
		BEARISH_DARK_CLOUD_COVER,
		BULLISH_MARUBOZU,
		BEARISH_MARUBOZU
	}
}